---
- name: Install Dockge using Docker
  hosts: all
  become: true

  vars:
    dockge_port: 5001
    dockge_data_dir: /opt/dockge
    dockge_stacks_dir: /opt/stacks

  tasks:
    - name: Ensure Docker is installed
      apt:
        name: docker.io
        state: present
      when: ansible_distribution == "Ubuntu"

    - name: Ensure Docker Compose is installed
      apt:
        name: docker-compose
        state: present
      when: ansible_distribution == "Ubuntu"

    - name: Create Dockge data directory
      file:
        path: "{{ dockge_data_dir }}"
        state: directory
        owner: root
        group: root
        mode: '0755'

    - name: Create stacks directory
      file:
        path: "{{ dockge_stacks_dir }}"
        state: directory
        owner: root
        group: root
        mode: '0755'

    - name: Run Dockge container
      docker_container:
        name: dockge
        image: louislam/dockge:latest
        restart_policy: always
        ports:
          - "{{ dockge_port }}:5001"
        volumes:
          - "{{ dockge_data_dir }}:/app/data"
          - "{{ dockge_stacks_dir }}:/opt/stacks"
        env:
          DOCKGE_STACKS_DIR: "{{ dockge_stacks_dir }}"