   - name: Ensure required system packages are installed
     apt:
       name:
         - python3-pip
         - python3-venv
         - build-essential
         - libffi-dev
         - libssl-dev
         - python3-dev
         - gcc
         - make
         - python3-wheel
         - cython
       state: present