- name: Install Docker Compose
  hosts: localhost
  become: true

  tasks:
    - name: Update apt package cache
      apt:
        update_cache: yes

    - name: Ensure required system packages are installed
      apt:
        name:
          - python3-pip
          - build-essential
          - libffi-dev
          - libssl-dev
          - python3-dev
          - gcc
          - make
          - python3-wheel
          - cython3
          - python3-setuptools
        state: present

    - name: Upgrade pip globally
      command: pip3 install --upgrade pip setuptools wheel

    - name: Install docker-compose globally
      command: pip3 install docker-compose==1.29.2