---
- name: Mount NFS share
  hosts: all
  become: yes
  tasks:
    - name: Ensure NFS client is installed
      apt:
        name: nfs-common
        state: present
        update_cache: yes

    - name: Check if NFS share is already mounted
      command: mountpoint -q /mnt/linux_tools
      register: mount_check
      ignore_errors: yes

    - name: Create local mount directory if not mounted
      file:
        path: /mnt/linux_tools
        state: directory
        owner: root
        group: root
        mode: '0755'
      when: mount_check.rc != 0
      become: yes

    - name: Mount NFS share
      mount:
        path: /mnt/linux_tools
        src: filer:/volume1/linux-tools
        fstype: nfs
        state: mounted

    - name: Ensure NFS share is persistent across reboots
      lineinfile:
        path: /etc/fstab
        line: "filer:/volume1/linux_tools /mnt/linux_tools nfs defaults 0 0"
        state: present