---
- name: Set DNS to point to 10.0.0.10
  hosts: all
  become: yes
  tasks:
    - name: Backup existing resolv.conf
      copy:
        src: /etc/resolv.conf
        dest: /etc/resolv.conf.bak
        remote_src: yes
        force: yes

    - name: Set DNS to 10.0.0.10
      lineinfile:
        path: /etc/resolv.conf
        line: "nameserver 10.0.0.10"
        state: present
        create: yes