---
- name: Enable root SSH login
  hosts: all
  become: yes
  tasks:
    - name: Ensure PermitRootLogin is set to yes
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^#?PermitRootLogin'
        line: 'PermitRootLogin yes'
        state: present
        backup: yes

    - name: Restart SSH service
      service:
        name: ssh.service
        state: restarted