- name: Install Docker Compose
  hosts: localhost
  become: true

  tasks:
    - name: Update apt package cache
      apt:
        update_cache: yes

    - name: Ensure required system packages are installed
      apt:
        name:
          - build-essential
          - libffi-dev
          - libssl-dev
          - python3-pip
          - python3-setuptools
          - python3-wheel
          - gcc
          - make
        state: present

    - name: Install Docker Compose using apt
      apt:
        name: docker-compose
        state: present